---
- name: Chargement des variables
  ansible.builtin.include_vars:
    file: ../vars/flatpak-fedora_to_install.yml

- name: Chargement des variables
  ansible.builtin.include_vars:
    file: ../vars/flathub_to_install.yml

- name: Installer les applications Flatpak depuis Flathub
  command: flatpak install -y flathub "{{ item }}"
  loop: "{{ flathub_apps }}"
  ignore_errors: true

- name: Installer les applications Flatpak depuis Fedora
  command: flatpak install -y fedora "{{ item }}"
  loop: "{{ fedora_apps }}"
  ignore_errors: true
