flathub_apps:
  - "md.obsidian.Obsidian"
  - "net.lutris.Lutris"
  - "org.deluge_torrent.deluge"
  - "com.parsecgaming.parsec"
  - "com.discordapp.Discord"
  - "org.filezillaproject.Filezilla"
  - "org.ryujinx.Ryujinx"
  - "org.kde.okular"
  - "com.moonlight_stream.Moonlight"
  - "dev.lizardbyte.app.Sunshine"
  - "com.pokemmo.PokeMMO"
  - "io.podman_desktop.PodmanDesktop"
  - "org.gnome.Extensions"
  - "com.mattjakeman.ExtensionManager"
  - "com.vivaldi.Vivaldi"
  - "com.heroicgameslauncher.hgl"
  - "io.github.mandruis7.xbox-cloud-gaming-electron"
  - "com.valvesoftware.Steam"
  - "com.spotify.Client"
  - "com.usebottles.bottles"
  - "io.github.lime3ds.Lime3DS"
  - "com.github.IsmaelMartinez.teams_for_linux"
  - "com.anydesk.Anydesk"
  - "org.torproject.torbrowser-launcher"
  - "io.github.mahmoudbahaa.outlook_for_linux"
  - "com.microsoft.AzureStorageExplorer"
  - "com.jgraph.drawio.desktop"
  - "com.jetbrains.PyCharm-Community"
  - "com.microsoft.Edge"
