---
- name: Configurer OneDrive et personnaliser l'environnement shell
  hosts: all  
  become: yes  
  tasks:
    - name: Créer un dossier OneDrive dans le répertoire Home de {{ ansible_env.USER }}
      file:
        path: "/home/{{ ansible_env.USER }}/OneDrive" 
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0755'

    - name: Créer ou modifier .bashrc pour ajouter un alias rclone au shell de {{ ansible_env.USER }}
      lineinfile:
        path: "/home/{{ ansible_env.USER }}/.bashrc"
        line: 'alias onedrive="rclone --vfs-cache-mode writes mount OneDrive: ~/OneDrive &"'
        insertafter: EOF
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0644'

    - name: Ajouter neofetch à la fin du .bashrc de {{ ansible_env.USER }}
      lineinfile:
        path: "/home/{{ ansible_env.USER }}/.bashrc"
        line: 'neofetch'
        insertafter: EOF
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0644'
    
    - name: Créer un dossier de cache pour tldr pour l'utilisateur {{ ansible_env.USER }}
      file:
        path: "/home/{{ ansible_env.USER }}/.cache/tldr"
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0755'
